config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, except: [:new, :create] do
    resources :bookingtours, only: [:show, :destroy]
  end

  resources :reviews, only: [:show, :destroy]
  resources :tours, only: [:index, :show] do
    resources :reviews, only: [:new, :show, :create]
    resources :bookingtours, only: [:create, :new]
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  scope :sort_by_created_at, ->{order created_at: :desc}
  belongs_to :category
  has_many :booking_tours
  has_many :reviews
  has_many :comments, as: :commentable
  has_many :imagerelations, as: :imagetable
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  def index
    @tours = Tour.sort_by_created_at.paginate page: params[:page],
      per_page: Settings.tour.length
  end

  def show
    @tours = Tour.find_by id: params[:id]
    @comments = @tours.comments.sort_by_created_at
    return if @tours
    flash[:danger] = t "controllers.reviews.notfound"
    redirect_to root_path
  end
end

app/views/tours/_tour.html.erb
<li>
  <%= link_to image_tag("property_1.jpg", class: "property_img"), root_path %>
  <span class="price"><%= number_to_currency(tour.price) %></span>
  <div class="property_details">
    <h1>
      <p><%= link_to tour.name, tour %></p>
      <p><%= link_to "-(#{tour.category.name})", tour %></p>
    </h1>
    <h2><%= "#{tour.place}, #{tour.food}, #{tour.new}" %>
      <span class="property_size"></span>
    </h2>
    <% if logged_in? %>
      <%= link_to t(".review"), new_tour_review_url(tour),
        class: "glyphicon glyphicon-edit" %>
      <%= link_to t(".booking"), new_tour_bookingtour_url(tour),
        class: "glyphicon glyphicon-edit" %>
    <% end %>
  </div>
</li>

app/views/tours/index.html.erb
<section class="listings">
  <div class="wrapper">
    <%= will_paginate %>
      <%= render "shared/item_tours" %>
    <%= will_paginate %>
  </div>
</section>  <!--  end listing section  -->

app/views/tours/show.html.erb
<div class="row">
  <div class="introduction_tour">
    <p>
      <%= link_to @tours.name %>
    </p>
    <p>
      <%= link_to t ".price"%>
      <%= number_to_currency(@tours.price) %>
    </p>
    <p>
      <%= link_to t ".food"%>
    </p>
    <p><%= @tours.food %></p>
    <p>
      <%= link_to t ".place" %>
    </p>
    <p><%= @tours.place %></p>
    <p><%= link_to t ".image" %></p>
  </div>
  <div class="image_tour">
    <%= link_to image_tag("https://c8.alamy.com/comp/F1WJN3/full-moon-harvest-moon-large-file-size-F1WJN3.jpg") %>
  </div>
</div>
<div class="row">
  <div class="comment_of_tour">
    <div class="tilte_comment">
      <p><%= t ".comment" %></p>
    </div>
    <%= form_for(:comment, url: tour_comments_url(@tours)) do |f| %>
      <%= f.text_area :content, cols: 10, rows: 5,
        placeholder: "#{t ".comment"}", class: "form-control, input100" %>
      <button class="button_show"><%= t ".comment" %></button>
    <% end %>
    <%= render partial: "comments/comment", collection: @comments %>
  </div>
</div>