config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, except: [:new, :create] do
    resources :bookingtours, only: [:show, :destroy]
  end

  resources :reviews, only: [:show, :destroy]
  resources :tours, only: [:index, :show] do
    resources :reviews, only: [:new, :show, :create]
    resources :bookingtours, only: [:create, :new]
  end
end

app/models/booking_tour.rb
class BookingTour < ApplicationRecord
  belongs_to :user
  belongs_to :tour
  enum status: {start: 0, started: 1}
  delegate :name, to: :tour, prefix: :tour
end

app/controllers/bookingtours_controller.rb
class BookingtoursController < ApplicationController
  before_action :load_tour, only: [:create, :new]

  def new
    @bookingtour = @tour.booking_tours.build
  end

  def create
    @bookingtour = current_user.booking_tours.create(bookingtour_params)
    ActiveRecord::Base.transaction do
      @bookingtour.save
      subtraction_qty
      flash[:success] = t "controllers.bookingtours.create.success"
      redirect_to root_path
    end
  rescue StandardError
    flash[:danger] = t "controllers.bookingtours.create.danger"
    redirect_to request.referrer || root_url
  end

  private

  def load_tour
    @tour = Tour.find_by id: params[:tour_id]
    return if @tour
    flash[:danger] = t "controllers.bookingtours.load_tour.danger"
    redirect_to root_path
  end

  def bookingtour_params
    params.require(:booking_tour).permit :name, :phone, :address,
      :amountpeople, :tour_id
  end

  def subtraction_qty
    quantity = @tour.amountpeople - @bookingtour.amountpeople
    @tour.update_attributes amountpeople: quantity
  end
end

app/views/bookingtours/_booking_tour.html.erb
<div class="panel panel-default panel-google-plus">
  <div class="panel-heading">
    <img class="img-circle pull-left" src="https://public.slidesharecdn.com/images/user-48x48.png" alt="Mouse0270" />
    <h3><%= booking_tour.tour_name %></h3>
    <h5><span><%= time_ago_in_words(booking_tour.created_at) %></span></h5>
  </div>
  <div class="panel-footer">
    <% if current_user? booking_tour.user %>
      <%= link_to t(".delete"), user_bookingtour_url(bookingtour_id: booking_tour.id), method: :DELETE,
        data: { confirm: t(".confirm") } %>
    <% end %>
  </div>
</div>

app/views/bookingtours/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@bookingtour, url: tour_bookingtours_path) do |f| %>
    <%= f.hidden_field :tour_id %>
    <%= f.label t ".fullname" %>
    <%= f.text_field :name, class: "form-control" %>

    <%= f.label t ".phone" %>
    <%= f.text_field :phone, class: "form-control" %>

    <%= f.label t ".address" %>
    <%= f.text_field :address, class: "form-control" %>

    <p><%= t ".tour" %><%= @tour.name %></p>

    <p><%= t ".price" %><%= number_to_currency(@tour.price) %></p>

    <p><%= t ".startdate" %><%= l @tour.startdate, format: :default %> </p>

    <%= f.label t ".amountpeople" %>
    <%= f.text_field :amountpeople, class: "form-control" %>

    <%= f.submit t(".book"), class: "btn btn-primary", data: { confirm: t(".confirm") } %>
      
    <% end %>
  </div>
</div>

app/views/bookingtours/show.html.erb
<div class="row">
  <div class="col-md-8">
    <%= render "shared/item_booking" %>
  </div>
  <div class="col-md-4">
  </div>
</div>