config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"

  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, except: [:new, :create] do
    resources :bookingtours, only: [:show, :destroy]
  end

  resources :reviews, only: [:show, :destroy]
  resources :tours, only: [:index, :show] do
    resources :reviews, only: [:new, :show, :create]
    resources :bookingtours, only: [:create, :new]
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="wrapper footer">
    <ul>
      <li class="links">
        <ul>
          <li><%= link_to t(".about"), "#" %></li>
          <li><%= link_to t(".support"), "#" %></li>
          <li><%= link_to t(".contact"), "#" %></li>
        </ul>
      </li>

      <li class="links">
        <ul>
          <li><%= link_to t(".about"), "#" %></li>
          <li><%= link_to t(".support"), "#" %></li>
          <li><%= link_to t(".contact"), "#" %></li>
        </ul>
      </li>

      <li class="links">
        <ul>
          <li><%= link_to t(".about"), "#" %></li>
          <li><%= link_to t(".support"), "#" %></li>
          <li><%= link_to t(".contact"), "#" %></li>
        </ul>
      </li>

      <li class="about">
        <p><%= t(".caption") %></p>
        <ul>
          <li><a href="http://facebook.com/pixelhint" class="facebook" target="_blank"></a></li>
          <li><a href="http://twitter.com/pixelhint" class="twitter" target="_blank"></a></li>
          <li><a href="http://plus.google.com/+Pixelhint" class="google" target="_blank"></a></li>
          <li><a href="#" class="skype"></a></li>
        </ul>
      </li>
    </ul>
  </div>

  <div class="copyrights wrapper">
    Copyright © 2015 <a href="http://pixelhint.com" target="_blank" class="ph_link" title="Download more free Templates">Pixelhint.com</a>. All Rights Reserved.
  </div>
</footer><!--  end footer  -->

app/views/layouts/_header.html.erb
<section class="hero">
  <header>
    <div class="wrapper">
      <%= link_to image_tag("logo.png", class: "logo"), root_path %>
      <a href="#" class="hamburger"></a>
      <nav>
        <ul>
          <li><%= link_to t(".home"), root_path %></li>
          <li><%= link_to t(".tours"), tours_path %></li>
          <li><%= link_to t(".reviews"), "#" %></li>
          <li><%= link_to t(".bookingnow"), "#" %></li>
          <li><%= link_to t(".about"), "#" %></li>
          <li><%= link_to t(".contact"), "#" %></li>
        </ul>
        <% if logged_in? %>
          <%= link_to t(".logout"), logout_path, class: "login_btn", method: :delete %>
          <%= link_to t(".profile"), current_user, class: "login_btn" %>
        <% else %>
          <%= link_to t(".login"), login_path, class: "login_btn" %>
        <% end %>
      </nav>
    </div>
  </header><!--  end header section  -->

    <section class="caption">
      <h2 class="caption"><%= t ".caption" %></h2>
      <h3 class="properties"><%= t ".properties" %></h3>
    </section>
</section><!--  end hero section  -->

app/views/layouts/_header_user.html.erb
<div class="row">
  <div class="col-md-12">
    <div class = "container">
      <div class="row">
        <ul class="nav nav-tabs" role="tablist">
          <li><%= link_to t(".home"), root_path %></li>
          <li><%= link_to t(".profile"), current_user %></li>
          <li><%= link_to t(".editpr"), edit_user_path %></li>
          <li><%= link_to t(".mybooking"), user_bookingtour_path(current_user) %></li>
        </ul>
        <div class="card hovercard">
          <div class="cardheader">
          </div>
          <div class="avatar">
            <img alt="" src="http://lorempixel.com/100/100/people/9/">
          </div>
          <% if @user.present? %>
            <div class="info">
              <div class="title">
                <a target="_blank" href="https://scripteden.com/"><%= @user.fullname %></a>
              </div>
              <div class="desc"><%= @user.email %></div>
              <div class="desc"><%= @user.phone %></div>
              <div class="desc"><%= @user.address %></div>
            </div>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= link_to t(".english"), locale: Settings.en %>
    <%= link_to t(".vietnamese"), locale: Settings.vi %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <div class="site-wrap">
        <%= render "layouts/header" %>
          <%= yield %>
        <%= render "layouts/footer" %>
      </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application",
      media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= link_to t(".english"), locale: Settings.en %>
    <%= link_to t(".vietnamese"), locale: Settings.vi %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="site-wrap">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/reviews.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application",
      media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= link_to t(".english"), locale: Settings.en %>
    <%= link_to t(".vietnamese"), locale: Settings.vi %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <div class="site-wrap">
      <%= render "layouts/header" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/signup.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t(".bookingtours") %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <div class="site-wrap">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= render "layouts/header_user" %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>